const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const state = { replay:null, stationId:'anand-vihar', hour:0, fireReduction:0, playing:false, playSpeed:1, selectedPage:'overview', selectedMetric:'aqi', sourceStations:null, sourceStationId:'2860223', archiveMode:'air', archivePlace:'Delhi', archiveProduct:'forecast_archive', archiveVariable:'PM2.5', archiveHours:72 };
let overviewMarkup=$('#content').innerHTML;
const stationXY = s => ({x:450+(s.lon-77.2)*520, y:260-(s.lat-28.6)*660});
const avg = (rows,key) => rows.reduce((a,r)=>a+r[key],0)/Math.max(rows.length,1);
const integerFormat = new Intl.NumberFormat('en-IN', { maximumFractionDigits:0 });
const fmt = n => integerFormat.format(Math.round(n));
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

async function api(path, options={}) { const res=await fetch(path,options); if(!res.ok) throw Error(`${res.status} ${path}`); return res.json(); }
const airVariables = [['PM2.5','PM2.5'],['PM10','PM10'],['NO2','NO₂'],['NOx','NOx'],['O3','O₃'],['CO','CO'],['SO2','SO₂'],['temperature','Temperature'],['relative_humidity','Relative humidity'],['wind_speed','Wind speed'],['wind_direction','Wind direction']];
const metVariables = { reanalysis:[['temperature_2m','Temperature'],['relative_humidity_2m','Relative humidity'],['surface_pressure','Surface pressure'],['wind_speed_10m_ms','Wind speed'],['wind_direction_10m','Wind direction'],['cloud_cover','Cloud cover'],['precipitation','Precipitation']], forecast_archive:[['temperature_2m','Temperature'],['dew_point_2m','Dew point'],['relative_humidity_2m','Relative humidity'],['surface_pressure','Surface pressure'],['wind_speed_10m_ms','Wind speed'],['wind_direction_10m','Wind direction'],['cloud_cover','Cloud cover'],['precipitation','Precipitation'],['boundary_layer_height_m','PBL height'],['shortwave_radiation','Shortwave radiation']] };
const sourcePlaces = ['AnandVihar_NCR','Ballabgarh','Delhi','Faridabad','Ghaziabad','Gurugram','Hapur','Manesar','Noida','Sonipat'];
function renderSeries(records, unit, label) {
  const valid=records.filter(point=>Number.isFinite(point.value));
  if(!valid.length)return '<div class="archive-empty">No valid values in this interval. The source fields remain unavailable; no values were filled.</div>';
  const w=900,h=260,p={l:54,r:18,t:18,b:34},values=valid.map(x=>x.value),lo=Math.min(...values),hi=Math.max(...values),span=Math.max(1e-9,hi-lo),x=i=>p.l+i/(records.length-1||1)*(w-p.l-p.r),y=v=>p.t+(hi-v)/span*(h-p.t-p.b);
  const chunks=[];let run=[];records.forEach((point,i)=>{if(Number.isFinite(point.value))run.push(`${run.length?'L':'M'}${x(i).toFixed(2)},${y(point.value).toFixed(2)}`);else if(run.length){chunks.push(run.join(' '));run=[]}});if(run.length)chunks.push(run.join(' '));
  const grid=[0,.5,1].map(r=>{const value=hi-r*span;return `<line x1="${p.l}" x2="${w-p.r}" y1="${y(value)}" y2="${y(value)}" class="chart-grid"/><text x="${p.l-8}" y="${y(value)+4}" text-anchor="end">${value.toLocaleString('en-IN',{maximumFractionDigits:1})}</text>`}).join('');
  const lines=chunks.map(path=>`<path d="${path}" class="archive-line"/>`).join('');
  const circles=records.map((point,i)=>Number.isFinite(point.value)?`<circle cx="${x(i)}" cy="${y(point.value)}" r="2.5"><title>${new Date(point.timestamp_utc).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}: ${point.value} ${esc(unit)}</title></circle>`:'').join('');
  const dates=[valid[0].timestamp_utc,valid[Math.floor((valid.length-1)/2)].timestamp_utc,valid.at(-1).timestamp_utc].map(t=>`<text x="${p.l+(valid.indexOf(valid.find(x=>x.timestamp_utc===t))/(records.length-1||1))*(w-p.l-p.r)}" y="${h-8}" text-anchor="middle">${new Date(t).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short'})}</text>`).join('');
  return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(label)} time series, ${valid.length} valid values in ${esc(unit)}"><title>${esc(label)}</title>${grid}${lines}${circles}${dates}</svg>`;
}
function archiveControls() {
  const air=state.archiveMode==='air', vars=air?airVariables:metVariables[state.archiveProduct], selectedStation=state.sourceStations?.find(s=>s.id===state.sourceStationId);
  return `<div class="archive-controls"><label>Dataset<select id="archive-mode"><option value="air" ${air?'selected':''}>OpenAQ observations</option><option value="met" ${!air?'selected':''}>Meteorology archive</option></select></label>${air?`<label>Station<select id="archive-station">${(state.sourceStations||[]).map(s=>`<option value="${esc(s.id)}" ${s.id===state.sourceStationId?'selected':''}>${esc(s.name)}${s.district?` · ${esc(s.district)}`:''}</option>`).join('')}</select></label>`:`<label>Product<select id="archive-product"><option value="forecast_archive" ${state.archiveProduct==='forecast_archive'?'selected':''}>Historical forecast archive</option><option value="reanalysis" ${state.archiveProduct==='reanalysis'?'selected':''}>ERA5 reanalysis</option></select></label><label>Location<select id="archive-place">${sourcePlaces.map(place=>`<option ${place===state.archivePlace?'selected':''}>${place}</option>`).join('')}</select></label>`}<label>Variable<select id="archive-variable">${vars.map(([value,name])=>`<option value="${esc(value)}" ${value===state.archiveVariable?'selected':''}>${name}</option>`).join('')}</select></label><label>Window<select id="archive-hours"><option value="72" ${state.archiveHours===72?'selected':''}>72 hours</option><option value="168" ${state.archiveHours===168?'selected':''}>7 days</option><option value="720" ${state.archiveHours===720?'selected':''}>30 days</option></select></label></div>${air&&selectedStation?`<p class="archive-selection">${esc(selectedStation.provider||'Provider unavailable')}${selectedStation.owner?` · ${esc(selectedStation.owner)}`:''} · ${selectedStation.latitude?.toFixed(4)??'—'}°N, ${selectedStation.longitude?.toFixed(4)??'—'}°E · ${selectedStation.has_normalized_observations?'normalized sample present':'no normalized sample rows'}</p>`:''}`;
}
function drawSourceMap() {
  const svg=$('#source-map');if(!svg||!state.sourceStations?.length)return;
  const stations=state.sourceStations,valid=stations.filter(s=>Number.isFinite(s.latitude)&&Number.isFinite(s.longitude)),minLon=Math.min(...valid.map(s=>s.longitude)),maxLon=Math.max(...valid.map(s=>s.longitude)),minLat=Math.min(...valid.map(s=>s.latitude)),maxLat=Math.max(...valid.map(s=>s.latitude)),x=s=>35+(s.longitude-minLon)/(maxLon-minLon)*830,y=s=>25+(maxLat-s.latitude)/(maxLat-minLat)*280;
  svg.innerHTML=`<title>OpenAQ station coordinates across the configured regional search area</title><path class="source-map-axis" d="M35 305H865M35 25V305"/><text x="35" y="326">${minLon.toFixed(2)}°E</text><text x="865" y="326" text-anchor="end">${maxLon.toFixed(2)}°E</text><text x="25" y="31" text-anchor="end">${maxLat.toFixed(2)}°N</text><text x="25" y="305" text-anchor="end">${minLat.toFixed(2)}°N</text>${valid.map(s=>`<g class="source-station ${s.has_normalized_observations?'has-sample':''} ${s.id===state.sourceStationId?'selected':''}" transform="translate(${x(s).toFixed(2)} ${y(s).toFixed(2)})" data-station="${esc(s.id)}" tabindex="0" role="button" aria-label="Select ${esc(s.name)}${s.has_normalized_observations?', normalized sample available':', station metadata only'}"><circle class="source-hit" r="8"/><circle class="source-point" r="${s.id===state.sourceStationId?4:2.5}"/><title>${esc(s.name)} · ${s.has_normalized_observations?'normalized sample available':'no normalized sample'}</title></g>`).join('')}`;
  svg.querySelectorAll('.source-station').forEach(marker=>{const select=()=>{state.sourceStationId=marker.dataset.station;renderArchive()};marker.addEventListener('click',select);marker.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}})});
}
async function loadArchive() {
  const chart=$('#archive-chart'),meta=$('#archive-meta');if(!chart||!meta)return;
  chart.innerHTML='<div class="archive-loading">Loading source records…</div>';meta.textContent='';
  try {
    const query=state.archiveMode==='air'?`/api/data/air-quality?station_id=${encodeURIComponent(state.sourceStationId)}&variable=${encodeURIComponent(state.archiveVariable)}&hours=${state.archiveHours}`:`/api/data/meteorology?place=${encodeURIComponent(state.archivePlace)}&product=${state.archiveProduct}&variable=${encodeURIComponent(state.archiveVariable)}&hours=${state.archiveHours}`;
    const result=await api(query), valid=result.records.filter(point=>Number.isFinite(point.value));
    if(!chart.isConnected)return; // navigated away while the source query was in flight
    chart.innerHTML=renderSeries(result.records,result.unit,`${result.source} · ${state.archiveVariable}`);
    $('#archive-variable-title').textContent=`${state.archiveVariable} · ${result.unit}`;
    $('#archive-source-kind').textContent=state.archiveMode==='air'?'OBSERVATION':state.archiveProduct==='reanalysis'?'REANALYSIS':'FORECAST ARCHIVE';
    const coverage=result.coverage?.start_utc?`${new Date(result.coverage.start_utc).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} — ${new Date(result.coverage.end_utc).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST`:'No valid observations in this selection';
    meta.innerHTML=`<span>${esc(result.source)}</span><span>${valid.length.toLocaleString('en-IN')} valid · ${result.records.length.toLocaleString('en-IN')} intervals</span><span>${esc(coverage)}</span>`;
    $('#archive-limitations').innerHTML=result.limitations.map(text=>`<li>${esc(text)}</li>`).join('');
  } catch (error) { if(!chart.isConnected)return; chart.innerHTML='<div class="archive-empty" role="alert">Could not load this source table. Check the API and retry.</div>';meta.textContent='';$('#archive-limitations').innerHTML=''; }
}
function renderArchive() {
  const content=$('#content');
  content.innerHTML=`<div class="status-banner"><span class="status-mark" aria-hidden="true">i</span><span class="status-copy"><b>LOCAL DATA ARCHIVE</b><span>Observed records, reanalysis and historical forecast products are kept separate.</span></span></div><section class="archive-page"><div class="archive-intro"><div><p class="panel-kicker">SOURCE EXPLORER</p><h2>Measurements & weather archives</h2><p>Inspect normalized observations and historical meteorological fields from the files in this project.</p></div><a href="/api/data/status" target="_blank" rel="noreferrer">Source status</a></div><section class="archive-map-panel"><div><h3>Monitoring locations</h3><p>OpenAQ coordinates across the configured regional search area; solid markers have normalized sample rows.</p></div><svg id="source-map" viewBox="0 0 900 340" role="group" aria-label="Selectable OpenAQ station locations"></svg><div class="source-map-legend"><span><i class="has-sample"></i>Normalized sample present</span><span><i></i>Metadata only</span><b>${state.sourceStations?.length??220} locations · broader than Delhi NCR</b></div></section>${archiveControls()}<div class="archive-chart-panel"><div class="archive-chart-heading"><div><h3 id="archive-variable-title">${esc(state.archiveVariable)}</h3><p id="archive-meta" aria-live="polite"></p></div><span class="data-badge" id="archive-source-kind">${state.archiveMode==='air'?'OBSERVATION':state.archiveProduct==='reanalysis'?'REANALYSIS':'FORECAST ARCHIVE'}</span></div><div class="archive-chart" id="archive-chart" aria-live="polite"></div><ul class="archive-limitations" id="archive-limitations"></ul></div><div class="archive-note"><b>Coverage limits</b><span>Only the normalized sample is charted. Raw OpenAQ pages are not read by the browser; uncollected or missing values stay unavailable.</span></div></section><footer class="page-footer"><span>VayuSangam <i>·</i> source data</span><span>Times stored in UTC · shown in IST</span><span><a href="#overview" data-page="overview">Back to forecast desk</a></span></footer>`;
  const bind=()=>{
    $('#archive-mode').onchange=e=>{state.archiveMode=e.target.value;state.archiveVariable=state.archiveMode==='air'?'PM2.5':'boundary_layer_height_m';renderArchive()};
    $('#archive-station')?.addEventListener('change',e=>{state.sourceStationId=e.target.value;renderArchive()});
    $('#archive-product')?.addEventListener('change',e=>{state.archiveProduct=e.target.value;state.archiveVariable=e.target.value==='reanalysis'?'temperature_2m':'boundary_layer_height_m';renderArchive()});
    $('#archive-place')?.addEventListener('change',e=>{state.archivePlace=e.target.value;loadArchive()});
    $('#archive-variable').onchange=e=>{state.archiveVariable=e.target.value;loadArchive()};
    $('#archive-hours').onchange=e=>{state.archiveHours=Number(e.target.value);loadArchive()};
    $$('a[data-page="overview"]').forEach(a=>a.onclick=e=>{e.preventDefault();navigate('overview')});
  };
  const ready=state.archiveMode==='air'?(state.sourceStations?Promise.resolve():api('/api/data/stations').then(x=>{state.sourceStations=x.stations})):Promise.resolve();
  ready.then(()=>{if(!$('#archive-mode'))return;content.querySelector('.archive-controls').outerHTML=archiveControls();bind();drawSourceMap();loadArchive()}).catch(()=>{content.querySelector('.archive-controls').outerHTML='<div class="archive-empty" role="alert">Station metadata could not be loaded. Retry by reopening Data archive.</div>'});
}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function station(){return state.replay.station_forecasts.find(s=>s.id===state.stationId)||state.replay.station_forecasts[0]}
/** Forecast rows for the current hour, each tagged with its station id so the
 *  selected station can be resolved by id rather than silently falling back to the first row. */
function currentRows(){return state.replay.station_forecasts.map(s=>({id:s.id,name:s.name,district:s.district,lat:s.lat,lon:s.lon,...s.forecast[Math.min(state.hour,71)]}))}
function updateMap(){
  const g=$('#station-layer'); if(!g)return;
  const rows=currentRows();
  g.innerHTML=state.replay.station_forecasts.map(s=>{const p=stationXY(s), selected=s.id===state.stationId, val=s.forecast[Math.min(state.hour,71)];return `<g class="station-marker ${selected?'selected':''}" data-station="${s.id}" transform="translate(${p.x} ${p.y})" tabindex="0" role="button" aria-label="Select ${esc(s.name)}, AQI ${val.aqi}, ${esc(aqiCategory(val.aqi))}"><rect class="marker-frame ${selected?'visible':''}" x="-7" y="-7" width="14" height="14" rx="1"/><circle class="point" r="${selected?3.1:2.7}"/><text x="9" y="-8">${esc(s.name.toUpperCase())}</text></g>`}).join('');
  const showStationTooltip=el=>{const s=state.replay.station_forecasts.find(x=>x.id===el.dataset.station);const v=s.forecast[Math.min(state.hour,71)];const t=$('#map-tooltip'),map=$('#map-canvas').getBoundingClientRect(),target=el.getBoundingClientRect();t.innerHTML=`<b>${esc(s.name)}</b><br>AQI ${v.aqi} · ${esc(aqiCategory(v.aqi))}<br>PM2.5 ${v.pm25} µg/m³`;t.style.display='block';t.style.left=`${Math.max(8,Math.min(target.left-map.left+12,map.width-148))}px`;t.style.top=`${Math.max(8,target.top-map.top-34)}px`};
  g.querySelectorAll('.station-marker').forEach(el=>{el.addEventListener('click',()=>selectStation(el.dataset.station));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectStation(el.dataset.station)}});el.addEventListener('pointerenter',()=>showStationTooltip(el));el.addEventListener('focus',()=>showStationTooltip(el));el.addEventListener('pointerleave',()=>$('#map-tooltip').style.display='none');el.addEventListener('blur',()=>$('#map-tooltip').style.display='none')});
  const fires=$('#fire-layer');fires.innerHTML=state.replay.smoke.fires.map((f,i)=>{let x=242+i*72,y=96+i*31;return `<g transform="translate(${x} ${y})"><path class="fire-marker" d="M0 -7 2 -2 7 0 2 2 0 7 -2 2 -7 0 -2 -2Z"/><text class="fire-label" x="9" y="3">FRP ${fmt(f.frp)}</text></g>`}).join('');
  const p=$('#particle-layer');const frame=(state.replay.smoke.particle_frames||[])[Math.min(state.hour,71)]||[];const pts=frame.filter((_,i)=>i%Math.max(1,Math.floor(frame.length/32))===0).slice(0,38);p.innerHTML=pts.map(o=>`<circle class="particle" cx="${235+(o.lon-76.3)*140}" cy="${72+(31.2-o.lat)*105}" r="${1+o.intensity*1.5}" style="opacity:${Math.min(.64,.15+o.intensity*.22)}"/>`).join('');
  updateHeat(rows);
}
function updateHeat(rows){const q=avg(rows,'aqi'), h1=$('#heat-a'),h2=$('#heat-b'),h3=$('#heat-c');if(!h1)return;const opacity=Math.min(.76,.3+q/620);h1.style.opacity=opacity;h2.style.opacity=opacity*.88;h3.style.opacity=opacity*.72}
function aqiCategory(a){return a<=50?'GOOD':a<=100?'SATISFACTORY':a<=200?'MODERATE':a<=300?'POOR':a<=400?'VERY POOR':'SEVERE'}
/** Map an AQI band onto the reference's state-fill vocabulary. */
function aqiFill(a){const c=aqiCategory(a);return c==='GOOD'?'ok':c==='SATISFACTORY'||c==='MODERATE'?'low':c==='POOR'?'warn':c==='VERY POOR'?'very-poor':'severe'}
/** Move the AQI marker and keep its accessible description in sync with the current reading. */
function updateAqiScale(value, category) {
  const pin=$('#aqi-pin'), scale=$('#aqi-scale');
  if(!pin||!scale)return;
  pin.style.left=`${Math.min(100,Math.max(0,value/500*100))}%`;
  scale.setAttribute('aria-label',`AQI scale, current value ${Math.round(value)} in the ${category.toLowerCase()} band`);
}
function updateChart(s){
  const box=$('#forecast-chart');
  if(!box)return;
  const series=s.forecast,key=state.selectedMetric,labels={aqi:['AQI proxy','index'],pm25:['PM2.5','µg/m³'],pm10:['PM10','µg/m³'],o3:['O₃','ppb'],no2:['NO₂','ppb']},vals=series.map(x=>x[key]),w=320,h=124,pad={l:35,r:6,t:8,b:8},min=0,max=Math.max(...vals)*1.12||1;
  const current=Math.min(state.hour,vals.length-1), x=i=>pad.l+i/(vals.length-1)*(w-pad.l-pad.r), y=v=>pad.t+(max-v)/(max-min)*(h-pad.t-pad.b);
  const line=vals.map((v,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' ');
  const hasInterval=key==='pm25',upper=series.map(v=>y(Math.min(max,v.pm25_p90))),lower=series.map(v=>y(Math.max(min,v.pm25_p10)));
  const band=upper.map((v,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${v.toFixed(1)}`).join(' ')+lower.map((_,n)=>{const i=lower.length-1-n;return ` L${x(i).toFixed(1)},${lower[i].toFixed(1)}`}).join(' ')+' Z';
  const ticks=[0,.33,.66,1].map(v=>Math.round(max*v));
  box.setAttribute('aria-label',`72-hour replay ${labels[key][0]} series in ${labels[key][1]}`);$('#interval-label').hidden=!hasInterval;
  box.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="72-hour replay ${labels[key][0]} time series"><title>72-hour replay ${labels[key][0]} · ${labels[key][1]}</title>${ticks.map(v=>`<line x1="${pad.l}" x2="${w-pad.r}" y1="${y(v)}" y2="${y(v)}" stroke="#B9C5AD"/><text x="0" y="${y(v)+3}" fill="#4f5c45" font-size="11">${v}</text>`).join('')}${hasInterval?`<path d="${band}" fill="#D3DCC9"/>`:''}<path d="${line}" fill="none" stroke="#606C38" stroke-width="2"/><line x1="${x(current)}" x2="${x(current)}" y1="${pad.t}" y2="${h-pad.b}" stroke="#C08E3A" stroke-dasharray="3 3"/><circle cx="${x(current)}" cy="${y(vals[current])}" r="3.5" fill="#E8EDDF" stroke="#606C38" stroke-width="2"/></svg>`;
}
function updateOverview(){if(!state.replay)return;const rows=currentRows(),r=rows.find(x=>x.id===state.stationId)||rows[0], selected=station(),regional=avg(rows,'aqi'),pblh=avg(rows,'pblh'),vc=avg(rows,'vc'),smoke=avg(rows,'smoke'),regionalCategory=aqiCategory(regional),stationCategory=aqiCategory(r.aqi);$('#kpi-aqi').textContent=fmt(regional);$('#kpi-category').textContent=regionalCategory;$('#kpi-category').dataset.category=regionalCategory;$('#kpi-pm').textContent=avg(rows,'pm25').toFixed(1);$('#kpi-o3').textContent=avg(rows,'o3').toFixed(1);$('#kpi-pblh').textContent=fmt(pblh);$('#kpi-vc').textContent=fmt(vc);$('#kpi-smoke').textContent=smoke.toFixed(2);$('#pblh-state').textContent=pblh<400?'Low':'Mixing';$('#vc-state').textContent=vc<650?'Stagnant':'Ventilated';$('#smoke-state').textContent=smoke>.5?'Plume near':'Low';$('#aqi-trend').textContent=`${avg(state.replay.station_forecasts.map(s=>s.forecast[Math.min(71,state.hour+24)]),'aqi')-regional>0?'+':''}${fmt(avg(state.replay.station_forecasts.map(s=>s.forecast[Math.min(71,state.hour+24)]),'aqi')-regional)}`;
  updateAqiScale(regional,regionalCategory);
  $('#pblh-state').dataset.fill=pblh<400?'low':'ok';$('#vc-state').dataset.fill=vc<650?'warn':'ok';$('#smoke-state').dataset.fill=smoke>.5?'warn':'ok';
  const alertCount=Number(avg(rows,'vc')<650)+Number(selected.forecast[Math.min(state.hour,71)].isi>2);$('.nav-count').textContent=alertCount;$('.nav-count').setAttribute('aria-label',`${alertCount} replay rules active`);
  $('#station-title').textContent=selected.name;$('#station-subtitle').textContent=`${selected.district} · Station forecast`;$('#drawer-station').textContent=`${selected.name} · ${selected.district}`;$('#drawer-aqi').textContent=r.aqi;$('#donut-value').textContent=r.aqi;$('#drawer-category').textContent=stationCategory;$('#drawer-category').dataset.category=stationCategory;$('#drawer-category').dataset.fill=aqiFill(r.aqi);$('#aqi-donut').dataset.category=stationCategory;$('#drawer-pm').innerHTML=`${r.pm25} <i>µg/m³</i>`;$('#drawer-o3').innerHTML=`${r.o3} <i>ppb</i>`;$('#drawer-no2').innerHTML=`${r.no2} <i>ppb</i>`;$('#valid-time').textContent=state.hour===0?'NOW · REPLAY':`T+${String(state.hour).padStart(2,'0')}H · REPLAY`;
  const future=selected.forecast[Math.min(71,state.hour)];['inversion','ventilation','smoke'].forEach(k=>{const el=$(`.driver[data-driver="${k}"] .driver-track i`);if(el)el.style.width=`${15+future.drivers[k]*85}%`});updateChart(selected);updateMap();
  const date=new Date(Date.UTC(2026,0,15,16,30)+state.hour*3600000),dateParts=Object.fromEntries(new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date).map(part=>[part.type,part.value]));$('#timeline-label').innerHTML=`${state.hour===0?'NOW':`+${state.hour}H`} <span>·</span> ${dateParts.day} ${dateParts.month.toUpperCase()}, ${dateParts.hour}:${dateParts.minute} IST`;
  $('#hour-readout').textContent=`T+${String(state.hour).padStart(2,'0')}:00`;
  const slider=$('#time-slider');slider.value=state.hour;slider.setAttribute('aria-valuetext',state.hour===0?'Now':`Plus ${state.hour} hours`);$('#range-progress').style.width=`${state.hour/72*100}%`;$('#map-subtitle').textContent=`AQI surface · Valid ${state.hour===0?'now':`+${state.hour}h`} · 6 monitoring locations`;
}
function selectStation(id){state.stationId=id;$('#insight-panel').classList.remove('is-collapsed');updateOverview();if(innerWidth<850)$('#insight-panel').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'})}
function svgLine(values,color='#606C38',height=170){const w=900,h=height,p=25,min=Math.min(...values),max=Math.max(...values),span=Math.max(1,max-min);const d=values.map((v,i)=>`${i?'L':'M'}${i/(values.length-1)*w},${h-p-(v-min)/span*(h-p*2)}`).join(' ');return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Smoke Influence Index over the replay horizon" preserveAspectRatio="none"><path d="M0 ${h-p}H${w}" stroke="#B9C5AD" stroke-dasharray="3 5"/><path d="${d}" fill="none" stroke="${color}" stroke-width="2.3" vector-effect="non-scaling-stroke"/>${values.map((v,i)=>i%12===0?`<line x1="${i/(values.length-1)*w}" x2="${i/(values.length-1)*w}" y1="${h-p}" y2="${h-p+4}" stroke="#8B9D83"/>`:``).join('')}</svg>`}
function svgCompare(series,height=190,normalize=false){const w=900,h=height,p=25,all=series.flatMap(x=>x.values),min=Math.min(...all),max=Math.max(...all),span=Math.max(1,max-min);const paths=series.map(s=>{const lo=Math.min(...s.values),hi=Math.max(...s.values),local=Math.max(1,hi-lo);const d=s.values.map((v,i)=>{const n=normalize?(v-lo)/local:(v-min)/span;return `${i?'L':'M'}${i/(s.values.length-1)*w},${h-p-n*(h-p*2)}`}).join(' ');return `<path d="${d}" fill="none" stroke="${s.color}" stroke-width="2.3" vector-effect="non-scaling-stroke"/>`}).join('');return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Forecast time-series comparison" preserveAspectRatio="none"><path d="M0 ${h-p}H${w}" stroke="#B9C5AD" stroke-dasharray="3 5"/>${paths}</svg>`}
function alertsMarkup(hourData){
  const ventilation=avg(currentRows(),'vc'),stagnant=ventilation<650,inversion=hourData.isi>2;
  const alerts=[stagnant?`<article class="wide-panel"><div class="eyebrow" style="color:#C08E3A">STAGNATION WATCH · REPLAY</div><h3>Low ventilation in the replay scenario</h3><p>Regional mean ventilation coefficient: ${fmt(ventilation)} m²/s. Prototype rule: below 650 m²/s.</p></article>`:'',inversion?`<article class="wide-panel"><div class="eyebrow" style="color:#7C3AED">INVERSION ACTIVE · REPLAY</div><h3>Thermal inversion signal at ${esc(station().name)}</h3><p>ISI: ${hourData.isi.toFixed(2)} °C. Prototype rule: T925 − T2m above 2 °C.</p></article>`:''].filter(Boolean);
  return `<div class="subpage"><div class="eyebrow">OPERATIONS · REPLAY RULES</div><h2 class="section-title">Forecast alerts</h2><p class="section-copy">Conditions are evaluated from the selected replay hour. These rules are prototype diagnostics, not public-health warnings.</p><div class="subpage-grid">${alerts.join('')||'<div class="verification-empty"><div><b>NO REPLAY RULE THRESHOLDS CROSSED</b><p>The ventilation and inversion checks are below their configured trigger levels for this hour.</p></div></div>'}</div></div>`;
}
function screen(page){const c=$('#content');if(page==='overview'){location.hash='overview';location.reload();return}
if(page==='archive'){renderArchive();return}
const data=station().forecast;const hourData=data[Math.min(state.hour,data.length-1)];let html='';
if(page==='inversion'){html=`<div class="subpage"><div class="eyebrow">BOUNDARY LAYER DIAGNOSTICS · 72H REPLAY</div><h2 class="section-title">Boundary-layer conditions</h2><p class="section-copy">Thermodynamic stability and mixing capacity shape pollutant accumulation conditions in the surrogate forecast.</p><div class="subpage-grid"><div class="metric-panel"><div class="label">INVERSION STRENGTH · ISI</div><div class="number">${hourData.isi>0?'+':''}${hourData.isi} °C</div><div class="desc">${hourData.isi>4?'Strong inversion active':'Weak / moderate inversion'} · T925 − T2m</div></div><div class="metric-panel"><div class="label">PLANETARY BOUNDARY LAYER</div><div class="number">${fmt(hourData.pblh)} m</div><div class="desc">${hourData.pblh<400?'Low mixing depth':'Daytime mixing depth'} · corrected met</div></div><div class="metric-panel"><div class="label">VENTILATION COEFFICIENT</div><div class="number">${fmt(hourData.vc)} <small style="font:12px var(--mono)">m²/s</small></div><div class="desc">${hourData.vc<650?'Stagnant':'Ventilated'} · PBLH × wind speed</div></div><article class="wide-panel"><div class="eyebrow">72H DIAGNOSTIC TIMELINE</div><h3>Stability & mixing evolution · normalized traces</h3><div class="large-chart">${svgCompare([{values:data.map(x=>x.isi),color:'#7C3AED'},{values:data.map(x=>x.pblh),color:'#606C38'},{values:data.map(x=>x.vc),color:'#B08B6E'}],210,true)}</div><div class="interval-key"><span><i style="background:#7C3AED"></i> ISI</span><span><i style="background:#606C38"></i> PBLH</span><span><i style="background:#B08B6E"></i> VC</span></div><div class="chart-axis"><span>NOW</span><span>+24H</span><span>+48H</span><span>+72H</span></div><p>Strong inversion + low ventilation → reduced vertical mixing → pollutant accumulation risk increased. This is a model process explanation, not a health forecast.</p></article></div></div>`}
else if(page==='plume'){const smoke=state.replay.smoke;html=`<div class="subpage"><div class="eyebrow">REGIONAL TRANSPORT · REPLAY PARTICLES</div><h2 class="section-title">Regional transport to NCR</h2><p class="section-copy">Lagrangian particle advection from deterministic demo fire points. No live FIRMS detections are connected.</p><div class="subpage-grid"><div class="metric-panel"><div class="label">DEMO FIRE POINTS</div><div class="number">03</div><div class="desc">FRP values are synthetic demo inputs</div></div><div class="metric-panel"><div class="label">RELATIVE SMOKE INFLUENCE</div><div class="number">${hourData.smoke.toFixed(2)}</div><div class="desc">Smoke Influence Index · unitless relative indicator</div></div><div class="metric-panel"><div class="label">NCR TRANSPORT WINDOW</div><div class="number">18–34 h</div><div class="desc">Illustrative ETA from replay scenario</div></div><article class="wide-panel"><div class="eyebrow">ADVECTION FIELD</div><h3>Northwest source region → Delhi NCR</h3><div class="large-chart">${svgLine(smoke.sii_grid.map(x=>x.sii),'#B08B6E',210)}</div><div class="chart-axis"><span>RELATIVE SII · NOW</span><span>+24H</span><span>+48H</span><span>+72H</span></div><p><b style="color:#C08E3A">Smoke Influence Index — relative transport indicator.</b> This is not an emissions inventory and does not represent observed fire detections.</p><div class="plume-summary"><span class="fire-count"><b>3</b><small>REPLAY SOURCES</small></span><div class="plume-direction"><span>Punjab region</span><i>··········➜</i><b>Delhi NCR</b></div><span class="eta-summary">PARTICLES <b>${smoke.particles.length}</b></span></div></article></div></div>`}
else if(page==='coupling'){const raw=data.map(x=>x.raw_pblh),cor=data.map(x=>x.pblh),coupled=data.map(x=>x.pm25),unc=data.map(x=>x.uncoupled_pm25);html=`<div class="subpage"><div class="eyebrow">MODEL ARCHITECTURE · PROTOTYPE SURROGATE</div><h2 class="section-title">Feedback at every forecast step</h2><p class="section-copy">The rollout feeds prior aerosol loading back into the next meteorological state. This is an explicit loop in the backend, not a UI-only diagram.</p><div class="wide-panel" style="margin-bottom:10px"><div class="flow-strip" style="justify-content:space-between;flex-wrap:wrap"><span>NWP input</span><i>→</i><span class="flow-active">Aerosol feedback ← previous PM₂.₅</span><i>→</i><span>Corrected T2m / PBLH / VC</span><i>→</i><span>PM₂.₅ + O₃ model</span><i>↺</i><span>Next timestep</span></div><p>SurrogateModelProvider · ${state.replay.coupled_steps} explicit hourly steps · prototype recurrence, not operational WRF-Chem.</p></div><div class="subpage-grid"><article class="wide-panel"><div class="eyebrow">RAW NWP VS FEEDBACK-CORRECTED</div><h3>PBL height · m</h3><div class="large-chart">${svgCompare([{values:raw,color:'#8B9D83'},{values:cor,color:'#606C38'}],190)}</div><div class="interval-key"><span><i style="background:#8B9D83"></i> Raw NWP surrogate</span><span><i style="background:#606C38"></i> Coupled corrected</span></div></article><article class="wide-panel"><div class="eyebrow">POLLUTION ROLLOUT COMPARISON</div><h3>PM₂.₅ coupled vs uncoupled · µg/m³</h3><div class="large-chart">${svgCompare([{values:unc,color:'#C66B3D'},{values:coupled,color:'#606C38'}],190)}</div><div class="interval-key"><span><i style="background:#C66B3D"></i> Uncoupled surrogate</span><span><i style="background:#606C38"></i> Coupled surrogate</span></div><p>Comparison is generated from illustrative surrogate logic; it is not evidence of forecast improvement.</p></article></div></div>`}
else if(page==='verify'){html=`<div class="subpage"><div class="eyebrow">MODEL SKILL · HISTORICAL EVALUATION</div><h2 class="section-title">Evaluation awaits verified observations</h2><p class="section-copy">Evaluation framework for coupled and baseline models. Scientific metrics remain empty until verified observations are connected.</p><div class="wide-panel"><div class="verification-empty"><div><b>VERIFICATION DATA REQUIRED</b><p>Connect a verified historical dataset to populate scientific skill metrics. Demo mode does not generate scientific accuracy claims.</p><span class="condition">NO SCIENTIFIC SCORES AVAILABLE</span></div></div><table class="data-table"><thead><tr><th>MODEL</th><th>MAE</th><th>RMSE</th><th>BIAS</th><th>HIGH AQI F1</th><th>INTERVAL COVERAGE</th></tr></thead><tbody>${['Coupled','Uncoupled','Persistence','CAMS'].map(m=>`<tr><td>${m}</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td></tr>`).join('')}</tbody></table><div class="range-ticks" style="padding-top:12px"><span>HORIZON</span><span>24H</span><span>48H</span><span>72H</span></div></div></div>`}
else if(page==='whatif'){html=`<div class="subpage"><div class="eyebrow">SCENARIO SIMULATION · PROTOTYPE</div><h2 class="section-title">Explore a source-reduction scenario</h2><p class="section-copy">Explore how a synthetic source reduction changes relative smoke transport and this surrogate PM2.5 forecast. This is not a policy intervention model.</p><div class="wide-panel"><div class="eyebrow">SCENARIO INPUT</div><h3>Fire emissions reduction</h3><div class="scenario-control"><span>0%</span><input id="scenario-slider" type="range" min="0" max="100" value="${state.fireReduction}" step="10" aria-label="Reduce demo fire emissions"><span>100%</span><b class="scenario-value" id="scenario-value">${state.fireReduction}%</b></div><button class="layer-button" id="run-scenario">Run scenario simulation</button><span id="scenario-status" class="section-copy" role="status" aria-live="polite" style="margin-left:10px"></span></div><div class="subpage-grid" style="margin-top:10px"><div class="metric-panel"><div class="label">BASELINE REGIONAL PM₂.₅ · +24H</div><div class="number" id="scenario-base">—</div><div class="desc">DEMO / REPLAY DATA</div></div><div class="metric-panel"><div class="label">SCENARIO PM₂.₅ · +24H</div><div class="number" id="scenario-result">—</div><div class="desc">Recomputed coupled surrogate</div></div><div class="metric-panel"><div class="label">SCENARIO DIFFERENCE</div><div class="number" id="scenario-delta">—</div><div class="desc">Illustrative difference · not policy impact</div></div><article class="wide-panel"><div class="eyebrow">FORECAST RESPONSE</div><h3>Regional mean PM₂.₅ · first 72 hours</h3><div class="large-chart" id="scenario-chart"></div></article></div></div>`}
else if(page==='alerts'){html=alertsMarkup(hourData)}
else {html=`<div class="subpage"><div class="eyebrow">LOGiNEXA · SIH 2026 · PS 26082</div><h2 class="section-title">6.5 minute judging walkthrough</h2><p class="section-copy">Follow the forecast story from regional state to coupled drivers, transport, scenario and verification.</p><div class="demo-steps">${[['01','Overview','overview'],['02','+48h forecast','overview'],['03','Station detail','overview'],['04','Inversion','inversion'],['05','Plume tracker','plume'],['06','Coupling','coupling'],['07','What-if scenario','whatif'],['08','Verification','verify']].map(x=>`<a class="demo-step" href="#${x[2]}" data-demo-hour="${x[1].includes('48h')?48:''}"><small>STEP ${x[0]}</small><b>${x[1]}</b></a>`).join('')}</div><div class="wide-panel" style="margin-top:12px"><div class="eyebrow">CORE STORY</div><h3>Regional fire activity → smoke transport → NCR exposure → inversion / low ventilation → pollutant accumulation → aerosol feedback → next forecast step</h3><p>All shown values are deterministic replay data for a workflow demonstration.</p></div></div>`}
if(page==='coupling'){const delta=hourData.pm25-hourData.uncoupled_pm25;html=html.replace('<div class="subpage-grid">','<div class="subpage-grid"><div class="metric-panel"><div class="label">COUPLED − UNCOUPLED PM₂.₅ · T+'+state.hour+'H</div><div class="number">'+(delta>0?'+':'')+delta.toFixed(1)+' µg/m³</div><div class="desc">Surrogate output difference · not a skill score</div></div>')}
c.innerHTML=`<div class="status-banner"><span class="status-icon">i</span><span><b>DEMO / REPLAY DATA</b><span> ${esc(state.replay.episode)} · Surrogate outputs · Not scientific validation</span></span><span class="banner-spacer"></span><span class="freshness">● DETERMINISTIC <b>72 STEPS</b></span></div>${html}<footer class="page-footer"><span>VayuSangam <i>×</i> LogiNexa</span><span>SIH 2026 · PS 26082</span><span>PROTOTYPE BUILD 0.3.0</span></footer>`;
if(page==='coupling')$$('.large-chart').forEach(ch=>{ch.style.position='relative';ch.children.length>1&&[...ch.children].forEach((svg,i)=>{svg.style.position='absolute';svg.style.inset='0';svg.style.opacity=i===0?'.75':'1'})});
$$('[data-demo-hour]').forEach(el=>el.onclick=e=>{let hour=Number(el.dataset.demoHour);if(hour){state.hour=hour;setTimeout(updateOverview,0)}});
if(page==='whatif'){
  const slider=$('#scenario-slider'), run=$('#run-scenario');$('#scenario-value').textContent=`${state.fireReduction}%`;
  const showScenario=(result)=>{const baseSeries=state.replay.station_forecasts[0].forecast.map((_,i)=>avg(state.replay.station_forecasts.map(s=>s.forecast[i]),'pm25'));const scenarioSeries=result.station_forecasts[0].forecast.map((_,i)=>avg(result.station_forecasts.map(s=>s.forecast[i]),'pm25'));const base=baseSeries[24],scenario=scenarioSeries[24];$('#scenario-base').textContent=base.toFixed(1);$('#scenario-result').textContent=scenario.toFixed(1);$('#scenario-delta').textContent=`${scenario-base>0?'+':''}${(scenario-base).toFixed(1)}`;$('#scenario-chart').innerHTML=`${svgCompare([{values:baseSeries,color:'#8B9D83'},{values:scenarioSeries,color:'#606C38'}],200)}<div class="interval-key"><span><i style="background:#8B9D83"></i> Replay baseline</span><span><i style="background:#606C38"></i> Scenario ${state.fireReduction}% reduction</span></div>`};
  slider.oninput=()=>{state.fireReduction=Number(slider.value);$('#scenario-value').textContent=`${state.fireReduction}%`};
  run.onclick=async()=>{run.disabled=true;$('#scenario-status').textContent='Computing coupled scenario…';try{const result=await api('/api/whatif/smoke',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fire_reduction:state.fireReduction})});showScenario(result);$('#scenario-status').textContent='Scenario complete · deterministic prototype';}catch(e){$('#scenario-status').textContent='Scenario unavailable · replay baseline retained';}finally{run.disabled=false}};
  run.click();
}
}
function navigate(page){state.selectedPage=page;$$('.nav-item').forEach(a=>{const active=a.dataset.page===page;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});const titles={overview:'Atmospheric overview',archive:'Data archive',inversion:'Inversion & ventilation',plume:'Smoke plume tracker',coupling:'Meteorology ↔ chemistry coupling',verify:'Forecast verification',alerts:'Forecast alerts',demo:'Demo walkthrough',whatif:'Scenario simulation'};$('#page-title').textContent=titles[page]||titles.demo;$('#crumb').textContent=(page==='demo'?'DEMO':page).toUpperCase();if(page==='overview'){if(!$('#kpis')){$('#content').innerHTML=overviewMarkup;bindOverview()}history.replaceState(null,'','#overview');updateOverview()}else{history.replaceState(null,'',`#${page}`);screen(page)}}
function renderPlayControl(){const button=$('#play-button');button.setAttribute('aria-label',state.playing?'Pause forecast':'Play forecast');button.setAttribute('aria-pressed',String(state.playing));button.innerHTML=`<svg class="button-icon" aria-hidden="true"><use href="${state.playing?'#icon-pause':'#icon-play'}"/></svg>`}
function startPlayback(){clearInterval(state.timer);state.timer=setInterval(()=>{if(state.hour>=72){state.playing=false;clearInterval(state.timer);renderPlayControl();return}state.hour+=1;updateOverview();if(state.hour===72){state.playing=false;clearInterval(state.timer);renderPlayControl()}},Math.max(180,720/state.playSpeed))}
function bindOverview(){
  $('#time-slider').addEventListener('input',e=>{state.hour=Number(e.target.value);updateOverview()});
  $('#play-button').addEventListener('click',()=>{state.playing=!state.playing;renderPlayControl();if(state.playing)startPlayback();else clearInterval(state.timer)});
  $('#speed-button')?.addEventListener('click',e=>{state.playSpeed=state.playSpeed===1?2:state.playSpeed===2?4:1;e.currentTarget.textContent=`${state.playSpeed}×`;e.currentTarget.setAttribute('aria-label',`Playback speed ${state.playSpeed} times faster; activate to change`);if(state.playing)startPlayback()});
  $('#chart-pollutant').addEventListener('change',e=>{state.selectedMetric=e.target.value;updateChart(station())});
  $('#layer-button').addEventListener('click',()=>{let m=$('.layer-menu');if(!m){m=document.createElement('div');m.id='layer-menu';m.className='layer-menu show';m.setAttribute('role','group');m.setAttribute('aria-label','Forecast map layers');m.innerHTML=[['aqi','Replay AQI surface'],['stations','Replay stations'],['fires','Replay fire seeds'],['smoke','Relative smoke particles']].map(([key,label])=>`<label><input type="checkbox" checked data-layer="${key}">${label}</label>`).join('');$('.map-panel').append(m);m.addEventListener('change',e=>{const selector={aqi:'#heat-layer',stations:'#station-layer',fires:'#fire-layer',smoke:'#particle-layer'}[e.target.dataset.layer];if(selector)$(selector).style.display=e.target.checked?'':'none'})}else m.classList.toggle('show');$('#layer-button').setAttribute('aria-expanded',String(m.classList.contains('show')))});
  $('.map-zoom').addEventListener('click',e=>{const action=e.target.closest('[data-zoom]')?.dataset.zoom;if(!action)return;if(action==='reset')state.mapZoom=1;else state.mapZoom=Math.min(2.2,Math.max(1,(state.mapZoom||1)*(action==='in'?.82:1.22)));const scale=state.mapZoom;$('#map-svg').setAttribute('viewBox',`${450-450/scale} ${245-245/scale} ${900/scale} ${490/scale}`)});
  $('#map-expand').addEventListener('click',async()=>{const panel=$('.map-panel');try{if(document.fullscreenElement)await document.exitFullscreen();else await panel.requestFullscreen()}catch{panel.classList.toggle('map-expanded')}});
  document.addEventListener('fullscreenchange',()=>$('#map-expand')?.setAttribute('aria-pressed',String(Boolean(document.fullscreenElement))));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('.layer-menu')){$('.layer-menu').classList.remove('show');$('#layer-button').setAttribute('aria-expanded','false')}});
  $('#open-station').addEventListener('click',()=>selectStation('anand-vihar'));$('.close-drawer').addEventListener('click',()=>$('#insight-panel').classList.add('is-collapsed'));
}
function bind(){window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)||'overview'));$$('.nav-item').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();navigate(a.dataset.page)}));$('.demo-link').addEventListener('click',e=>{e.preventDefault();navigate('demo')});$('.replay-control').addEventListener('click',()=>toast('Live sources are not connected. Showing deterministic replay data.'));bindOverview()}
async function init(){bind();try{state.replay=await api('/api/replay/delhi-winter-stagnation');updateOverview();navigate(location.hash.slice(1)||'overview')}catch(err){$('#content').innerHTML=`<div class="status-banner"><b>REPLAY API UNAVAILABLE</b> Start the FastAPI backend with <code>python -m uvicorn backend.app.main:app --reload</code>.</div>`;console.error(err)}}
init();
